### ISSUE TITLE
模拟器没有相机时，点拍照会崩溃

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/ImagePicker#1]
感谢作者分享开源，非常好的库，不过模拟器没有相机时，点拍照会崩溃

**Comment by Vanish136** [comment]
好的 下个版本会添加摄像头检查

**Comment by Vanish136** [comment]
@hegelsu  你可以尝试下V1.3.1版本

**Comment by hegelsu** [comment]
还是不行：
07-18 19:39:28.945 E/AndroidRuntime( 3303): FATAL EXCEPTION: main
07-18 19:39:28.945 E/AndroidRuntime( 3303): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE (has extras) }
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1634)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1429)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.app.Activity.startActivityForResult(Activity.java:3370)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.app.Activity.startActivityForResult(Activity.java:3331)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at com.lwkandroid.imagepicker.utils.TakePhotoCompatUtils.takePhoto(TakePhotoCompatUtils.java:69)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at com.lwkandroid.imagepicker.ui.grid.view.ImageDataActivity.doTakePhoto(ImageDataActivity.java:176)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at com.lwkandroid.imagepicker.ui.grid.view.ImageDataActivity.startTakePhoto(ImageDataActivity.java:170)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at com.lwkandroid.imagepicker.ui.grid.adapter.ImageCameraItemView$1.onClick(ImageCameraItemView.java:47)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.view.View.performClick(View.java:4204)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.view.View$PerformClick.run(View.java:17355)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.os.Handler.handleCallback(Handler.java:725)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.os.Handler.dispatchMessage(Handler.java:92)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.os.Looper.loop(Looper.java:137)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at android.app.ActivityThread.main(ActivityThread.java:5069)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at java.lang.reflect.Method.invoke(Method.java:511)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
07-18 19:39:28.945 E/AndroidRuntime( 3303): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by hegelsu** [comment]
另外，ImagePicker是否可以直接提供一个打开相机拍照的方法，这样我不必有两个入口来处理图片

**Comment by Vanish136** [comment]
@hegelsu 找到问题了，这个问题是因为海马玩模拟器没有默认的拍照应用，所以ImagePicker发出的Intent没有任何Activity去接收，你可以试试安装一个拍照应用，上述问题就不会出现了。一般实测还是以真实手机为准，现实中手机都会有默认的拍照应用，所以这个问题一般不会出现，当然我可以再发个小版本去兼容下这种特殊情况。

**Comment by hegelsu** [comment]
嗯，做下兼容肯定是最好的，毕竟现在的安卓手机环境也是五花八门。
