### ISSUE TITLE
无法发起拍照请求

### ISSUE THREAD

**Issue by onlycyndi** [Vanish136/ImagePicker#10]
你好，集成1.3.8拍照点击后提示“无法发起拍照请求”

**Comment by Vanish136** [comment]
@onlycyndi 这个提示的话很可能和具体ROM有关系了，方便告诉我你测试机的品牌、型号、Android版本吗？

**Comment by Vanish136** [comment]
@onlycyndi 我仔细分析了下这个问题可能产生的原因，大概率是你指定的缓存目录不是sd卡下的目录，而我在库中预设的FileProvider只考虑了sd卡的情况，是我的疏忽，下个版本马上修复这个问题。谢谢你的反馈！

**Comment by onlycyndi** [comment]
2018-05-29 00:47:32.561 19674-19674/com.test.will E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.will, PID: 19674
    java.lang.RuntimeException: Unable to resume activity {com.test.will/com.test.will.mvp.composedimage.PhotoActivity}: java.lang.RuntimeException: Failure delivering result 

ResultInfo{who=null, request=111, result=-1, data=Intent { (has extras) }} to activity {com.test.will/com.test.will.mvp.composedimage.PhotoActivity}: 

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.lwkandroid.imagepicker.data.ImageBean.getImagePath()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3485)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3525)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=111, result=-1, data=Intent { (has extras) }} to activity 

{com.test.will/com.test.will.mvp.composedimage.PhotoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String 

com.lwkandroid.imagepicker.data.ImageBean.getImagePath()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4162)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3459)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3525) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.lwkandroid.imagepicker.data.ImageBean.getImagePath()' on a null object 

reference
        at com.test.will.mvp.composedimage.PhotoActivity.onActivityResult(PhotoActivity.java:133)
        at android.app.Activity.dispatchActivityResult(Activity.java:7128)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4158)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3459) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3525) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6221)

**Comment by onlycyndi** [comment]
十分感谢你的帮助。上面是偶尔会报错的日志，可能是因为的手机和APP是横屏的问题，测试机是用的红米7.0的系统。用过其他第三方的选择库也是差不多的问题，不过你今天修复的这个至少能用了。

**Comment by Vanish136** [comment]
@onlycyndi 
谢谢你的反馈。
针对上面这个报错我尝试了好多次，用的也是红米，8.0系统，打开了自动旋转，横竖屏都试过了还是没能复现出来...所以只能通过报错提示搜了下可能存在的原因，目前你可以尝试在onActivityResult()里获取数据的时候，用下面的代码试试：
List<ImageBean> resultList = data.getExtras().getParcelableArrayList(ImagePicker.INTENT_RESULT_DATA);

希望有用吧
